### PR TITLE
Add view scaling activities 

### PR DESCRIPTION
**Pull request by amitaekbote**
Add JobActivityHistoryService
Note: this is the alpha version

### CODE REVIEW

**Review by gabrielhartmann — APPROVED** [review]

**Comment by gabrielhartmann** [comment]
Pagination has been removed which I think is possibly good.  I don't know how pagination would be implemented with a postgres backend, although I'm sure it's possible.  I'm also not sure how many results Spinnaker might want, or possibly if they would like an API providing the last N results or something?

**Comment by amitaekbote** [comment]
> Pagination has been removed which I think is possibly good. I don't know how pagination would be implemented with a postgres backend, although I'm sure it's possible. I'm also not sure how many results Spinnaker might want, or possibly if they would like an API providing the last N results or something?

I was going to limit the number of records to a specific number, given this is going to be in the UI I dont think unlimited number of records is useful

**Comment by amitaekbote** [comment]
will leave as draft till we finalize.

**Comment by gabrielhartmann** [comment]
> > Pagination has been removed which I think is possibly good. I don't know how pagination would be implemented with a postgres backend, although I'm sure it's possible. I'm also not sure how many results Spinnaker might want, or possibly if they would like an API providing the last N results or something?
> 
> I was going to limit the number of records to a specific number, given this is going to be in the UI I dont think unlimited number of records is useful

I don't know what the limitations are of clients of the API.  I'm not sure we should design the API with a baked in assumption that it's only client is the Spinnaker UI.  As a client of this API I would expect to be able to get all events if I asked for them.  Since the typical use case anticipated is that of the Spinnaker UI, it would be good to know what their current API supports.   Is it an unlimited length API etc?

**Pull request merged**
