### PR TITLE
Add validator endpoint for entrypoint and command

### PR DESCRIPTION
**Pull request by rgulewich**
This adds a validator endpoint for job `entrypoint` and `command`. It will return a sanitized version of entrypoint and command using the same logic that the titus-executor does.

### CODE REVIEW

**Review by corindwyer — APPROVED** [review]
Should we make a distinction between validators and sanitizers in this project or should we treat all operations like a validator but some validators can return sanitized results?

Both approaches are functionally the same, but wanted to get thoughts on organization/concepts.

**Comment by rgulewich** [comment]
> Should we make a distinction between validators and sanitizers in this project or should we treat all operations like a validator but some validators can return sanitized results?

Yeah, I was wondering that myself, @corindwyer .  @tbak , do you have preferences here?

The other thing I was wondering while making these changes: should I be adding [CacheMetadata](https://github.com/Netflix/titus-api-definitions/pull/131/files#diff-e383da3515444581d7b1bcc7f3aee6076da74b9a9676dfd918fb9dba7eca6f80R195) to every response object, regardless of how computationally expensive it is?  It makes obvious sense to add it for RPC calls that call out to AWS under the hood or are time-consuming, but I'm not sure if it does for calls that are more like simple checks.

**Review by tbak — APPROVED** [review]

**Comment by corindwyer** [comment]
@tbak I don't understand your comment as a sanitizer is something that does validation and rewriting/modifying of the value. In the existing project, there is a distinction between validators (true/false) versus sanitizers (rewrite value). I don't have a strong opinion if we keep the sanitizer name, but I would like it to be consistent going forward which means we would call everything a validator but some would have responses with different values than true/false.

**Comment by tbak** [comment]
@corindwyer I think I misunderstood you. I thought you wanted to separate validation and sanitization into two different API endpoints. If this is just about calling everything `validator`, I am ok with this.

**Comment by corindwyer** [comment]
@tbak yes, my comment was about aligning on naming. Aligning on `Validator` for all cases seems fine.

@rgulewich `CachedMetadata` is used to represent cached info from an external system. Since this API doesn't have an external dependency, I don't think you need it.

**Pull request merged**
